// <auto-generated />
namespace ControlGame.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criando_bd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criando_bd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812171912348_criando_bd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
