//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGame.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlGame.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é invalido.
        /// </summary>
        public static string X_0_INVALIDO {
            get {
                return ResourceManager.GetString("X_0_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatorio.
        /// </summary>
        public static string X_0_OBRIGATORIO {
            get {
                return ResourceManager.GetString("X_0_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe {0} no minimo com 6 caracteres.
        /// </summary>
        public static string X_6_QUANTIDADE {
            get {
                return ResourceManager.GetString("X_6_QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel alterar {0} que não esta ativo.
        /// </summary>
        public static string X_ALTERAR_INATIVO {
            get {
                return ResourceManager.GetString("X_ALTERAR_INATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atualizado com sucesso.
        /// </summary>
        public static string X_DADOS_ATUALIZADOS {
            get {
                return ResourceManager.GetString("X_DADOS_ATUALIZADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não encontrados.
        /// </summary>
        public static string X_DADOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("X_DADOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatorio e deve conter de {1} a {2} caracteres.
        /// </summary>
        public static string X_OBRIGATORIO_QUANTIDADE_RANGE {
            get {
                return ResourceManager.GetString("X_OBRIGATORIO_QUANTIDADE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ja existe.
        /// </summary>
        public static string X_OPERACAO_DUPLICIDADE {
            get {
                return ResourceManager.GetString("X_OPERACAO_DUPLICIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criacao realizada com sucesso.
        /// </summary>
        public static string X_OPERACAO_REALIZADA_SUCESSO {
            get {
                return ResourceManager.GetString("X_OPERACAO_REALIZADA_SUCESSO", resourceCulture);
            }
        }
    }
}
